// readme.mjs — render README.md's "What's in the belt" table from the toolbelt.json
// manifests. The manifests are the source of truth (`hits`, `surface`, optional
// `readme_label` — docs/MANIFEST.md); the README block between the two markers below is
// derived output, regenerated by `bin/toolbelt readme --write` and freshness-checked by
// `bin/toolbelt readme --check`. Zero dependencies; Node >=18.

export const BEGIN_MARKER =
  '<!-- belt-table:begin — derived from toolbelt.json manifests; edit hits/surface there, then bin/toolbelt readme --write -->';
export const END_MARKER = '<!-- belt-table:end -->';

// Row order and shape per kind. An unknown kind is a loud error rather than a silently
// dropped row.
const KIND_META = {
  tool: { icon: '🔧', dir: 'tools' },
  connector: { icon: '🔌', dir: 'connectors' },
  skill: { icon: '🎓', dir: 'skills' },
};
const KIND_ORDER = Object.keys(KIND_META);

/**
 * Render the belt table (header + one row per manifest) — tools, then connectors, then
 * skills, alphabetical within each kind. Cells come verbatim from each manifest's
 * `hits`/`surface`; a manifest missing either is an error naming the file, never a blank
 * cell — a blank cell would read as "nothing to say" rather than "nobody said it".
 */
export function renderTable(manifests) {
  const rows = ['| | Tool | Hits | Surface |', '|---|---|---|---|'];
  const sorted = [...manifests].sort((a, b) =>
    a.kind === b.kind ? a.name.localeCompare(b.name) : KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind),
  );
  for (const m of sorted) {
    const where = m._file ?? m.name;
    const meta = KIND_META[m.kind];
    if (!meta) throw new Error(`${where}: kind "${m.kind}" has no belt-table shape (expected ${KIND_ORDER.join('|')})`);
    for (const field of ['hits', 'surface']) {
      if (typeof m[field] !== 'string' || !m[field].trim()) {
        throw new Error(`${where}: missing "${field}" — every manifest needs hits + surface for the README belt table (docs/MANIFEST.md)`);
      }
    }
    const label = m.readme_label ?? `\`${meta.dir}/${m.name}\``;
    rows.push(`| ${meta.icon} | ${label} | ${m.hits} | ${m.surface} |`);
  }
  return rows.join('\n');
}

/** The full derived block: begin marker, table, end marker. */
export function renderBlock(manifests) {
  return `${BEGIN_MARKER}\n${renderTable(manifests)}\n${END_MARKER}`;
}

/**
 * Locate the marker-delimited block in README text.
 * @returns {{begin:number, end:number}|null} slice bounds including both markers, or null
 * when no begin marker exists. A begin without an end is corruption, not absence — throw.
 */
export function locateBlock(readme) {
  const begin = readme.indexOf(BEGIN_MARKER);
  if (begin === -1) return null;
  const end = readme.indexOf(END_MARKER, begin + BEGIN_MARKER.length);
  if (end === -1) throw new Error('README.md has the belt-table begin marker but no end marker');
  return { begin, end: end + END_MARKER.length };
}

/** The current marker-delimited block in README text, or null when there isn't one. */
export function currentBlock(readme) {
  const found = locateBlock(readme);
  return found ? readme.slice(found.begin, found.end) : null;
}

/**
 * Replace the belt-table block in README text with `block`, returning the new text.
 * Prefers the markers; on a first run (no markers yet) it replaces the legacy hand-written
 * table — the `| | Tool | Hits | Surface |` header line through the last consecutive
 * table row — so the markers land exactly where the old table was.
 */
export function replaceBlock(readme, block) {
  const found = locateBlock(readme);
  if (found) return readme.slice(0, found.begin) + block + readme.slice(found.end);

  const lines = readme.split('\n');
  const header = lines.findIndex((l) => l.trim() === '| | Tool | Hits | Surface |');
  if (header === -1) {
    throw new Error('README.md has neither belt-table markers nor the legacy "| | Tool | Hits | Surface |" table — nowhere to put the derived block');
  }
  let last = header;
  while (last + 1 < lines.length && lines[last + 1].startsWith('|')) last += 1;
  return [...lines.slice(0, header), block, ...lines.slice(last + 1)].join('\n');
}

/**
 * A short drift summary between the README's current block and the rendered one:
 * `{drifted, summary}` where `summary` names row counts added/stale plus a few examples.
 */
export function diffSummary(current, rendered) {
  if (current === rendered) return { drifted: false, summary: 'belt table matches the manifests' };
  if (current === null) return { drifted: true, summary: 'README.md has no belt-table markers' };
  const have = current.split('\n');
  const want = rendered.split('\n');
  const haveSet = new Set(have);
  const wantSet = new Set(want);
  const missing = want.filter((l) => !haveSet.has(l));
  const stale = have.filter((l) => !wantSet.has(l));
  const clip = (l) => (l.length > 100 ? `${l.slice(0, 97)}…` : l);
  const examples = [
    ...missing.slice(0, 3).map((l) => `  + ${clip(l)}`),
    ...stale.slice(0, 3).map((l) => `  - ${clip(l)}`),
  ];
  return {
    drifted: true,
    summary: `belt table drifts from the manifests (+${missing.length} line(s) to add, -${stale.length} stale)${examples.length ? `\n${examples.join('\n')}` : ''}`,
  };
}
