// {{TITLE}} — Theme
// Colors, fonts, sizing, and the section registry. Edit freely: this file is the book's
// visual identity and is never regenerated by the belt (scaffold refuses to overwrite it).

// === Section Colors ===
// One primary + one light variant per section group.
{{COLORS}}

// === Fonts ===
// System fonts by default; check a candidate with `typst fonts | grep "<name>"`.
#let font-body     = "{{FONT_BODY}}"
#let font-heading  = "{{FONT_HEADING}}"
#let font-mono     = "{{FONT_MONO}}"

// === Sizing ===
#let body-size    = 9.5pt
#let small-size   = 8pt
#let tiny-size    = 7pt
#let h1-size      = 18pt
#let h2-size      = 14pt
#let h3-size      = 11pt
#let h4-size      = 10pt

// === Section Registry ===
// Maps each chapter filename stem to (tab label, color, order). Tab labels render rotated
// 90° in a thin thumb tab — keep them to 8 characters.
#let sections = (
{{SECTIONS}}
)

#let total-tabs = {{TOTAL_TABS}}
